"""empty message

Revision ID: 750091039b7b
Revises: cd835c1ac49a
Create Date: 2020-02-27 04:10:47.267859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750091039b7b'
down_revision = 'cd835c1ac49a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=225), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
